import "./globals.css";
import type { Metadata } from "next";
import Main from "@/components/Main";
import ThemeProvider from "@/components/Providers/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <Main>{children}</Main>
      </ThemeProvider>
    </html>
  );
}
